version: '3.8'

services:
  frontend:
    build: ./clip-filter-frontend
    ports:
      - '80:80'

  backend:
    build: ./clip-filter-backend
    ports:
      - '5000:5000'
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0

  backend-tests:
    build: ./clip-filter-backend
    command: ["sh", "-c", "python test_unit.py && python test_integration.py"]
